### ISSUE TITLE
Query about read/write interface: why does read have a pos_ref, and write have a pos?

### ISSUE THREAD

**Issue by tomjridge** [janestreet/bin_prot#22]
Question as title. I don't mind, I just thought it looked a bit odd. What was the reasoning behind making the interfaces different in this way?

Thanks

**Comment by aalekseyev** [comment]
The reason is that the `read` function needs to return both the position it read to and the resulting value. We could return both of these values by wrapping them in a tuple, but that incurs an extra allocation. Storing the int into the ref using side-effect lets us avoid that allocation.

There is no corresponding problem with `write` because write only needs to return one thing, so we use the simpler interface.

**Comment by tomjridge** [comment]
Thank you @aalekseyev ! I had not considered the cost of the extra allocation.
